
export function About() {
    return(
       <div className="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ullamcorper at dui vel tincidunt. Cras venenatis, quam at varius hendrerit, nisi lacus fermentum dolor, eget mattis enim tellus in augue. Maecenas imperdiet posuere mauris, vitae dictum libero faucibus sed. Fusce maximus eros sed arcu rhoncus, id lobortis enim aliquam. Proin viverra diam vitae magna lobortis lacinia. Sed malesuada volutpat urna, nec condimentum sapien semper in. Quisque efficitur pharetra eros, dapibus aliquet turpis porttitor in.

       Aliquam dui diam, gravida tincidunt nunc nec, tempus semper elit. Suspendisse a congue justo. Mauris non risus sed ante tempor volutpat. Nullam semper augue ipsum, a consequat ligula blandit non. Pellentesque vel orci ac diam imperdiet eleifend et eget diam. Morbi urna mauris, dictum vitae leo sed, placerat lobortis ex. Phasellus accumsan vulputate ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vitae justo dui. Integer elementum leo nec vehicula varius. Nulla hendrerit porta scelerisque.
       
       In sit amet dui et quam scelerisque eleifend. Curabitur maximus nisi ut ornare volutpat. In hac habitasse platea dictumst. Donec sed ex malesuada felis hendrerit sagittis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed facilisis convallis nisl, et maximus ipsum commodo non. Curabitur eleifend malesuada nibh, in scelerisque tellus tempus vel. Sed scelerisque ipsum vel arcu luctus vehicula. Aliquam id ligula et urna aliquam pretium. Nunc efficitur odio lacinia odio lobortis varius. Curabitur magna dui, mollis quis faucibus eget, semper in nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus rhoncus diam orci, non tempor sapien hendrerit et.
       
       Donec vitae nisl ut quam laoreet porttitor sed non ligula. Morbi ut blandit dolor. Aenean venenatis vel turpis ut egestas. Ut malesuada sollicitudin dui vel lobortis. Nulla placerat porta nisl eu tempor. Nam molestie dapibus elit, non malesuada eros blandit ac. Pellentesque elit ipsum, tristique sit amet scelerisque ac, rutrum sed tellus. Ut a consequat nisi. Vivamus efficitur lorem id rutrum elementum. Suspendisse non nibh id lectus lacinia bibendum. Nunc at tempor dolor. Vivamus eu arcu vulputate, dictum tellus in, blandit tellus. Nunc mollis dictum risus in euismod. Mauris ex urna, blandit non auctor sit amet, volutpat in lorem. Maecenas ultricies felis augue, sed egestas velit viverra nec. In eu nunc dolor.
       
       Mauris non dignissim ligula, vel gravida urna. Aliquam tempus pellentesque augue, nec feugiat odio sodales vitae. Morbi ac pretium nisl, eu interdum velit. Nunc lobortis urna in magna rutrum vehicula. Nulla convallis dolor nec purus mattis, vel tempor felis aliquet. Suspendisse sagittis mattis neque id sodales. Etiam a porttitor quam, id pulvinar eros. Nulla ullamcorper gravida elementum. Phasellus eget risus odio. Maecenas a ligula at neque consequat commodo at eget lorem. Nullam sem orci, viverra euismod mauris vel, vulputate</div>
    )
}